/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Memory { 'imageData' : string, 'caption' : string }
export interface _SERVICE {
  'daysUntilNextBirthday' : ActorMethod<[], bigint>,
  'getBirthday' : ActorMethod<[], [bigint, bigint]>,
  'getBoyfriendName' : ActorMethod<[], string>,
  'getLetter' : ActorMethod<[], Array<string>>,
  'getMemories' : ActorMethod<[], Array<Memory>>,
  'isTodayBirthday' : ActorMethod<[], boolean>,
  'setBirthday' : ActorMethod<[bigint, bigint], undefined>,
  'setBoyfriendName' : ActorMethod<[string], undefined>,
  'setLetter' : ActorMethod<[Array<string>], undefined>,
  'setMemories' : ActorMethod<[Array<Memory>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];