/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Memory = IDL.Record({
  'imageData' : IDL.Text,
  'caption' : IDL.Text,
});

export const idlService = IDL.Service({
  'daysUntilNextBirthday' : IDL.Func([], [IDL.Int], ['query']),
  'getBirthday' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getBoyfriendName' : IDL.Func([], [IDL.Text], ['query']),
  'getLetter' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'isTodayBirthday' : IDL.Func([], [IDL.Bool], ['query']),
  'setBirthday' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setBoyfriendName' : IDL.Func([IDL.Text], [], []),
  'setLetter' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setMemories' : IDL.Func([IDL.Vec(Memory)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Memory = IDL.Record({ 'imageData' : IDL.Text, 'caption' : IDL.Text });
  
  return IDL.Service({
    'daysUntilNextBirthday' : IDL.Func([], [IDL.Int], ['query']),
    'getBirthday' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getBoyfriendName' : IDL.Func([], [IDL.Text], ['query']),
    'getLetter' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'isTodayBirthday' : IDL.Func([], [IDL.Bool], ['query']),
    'setBirthday' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setBoyfriendName' : IDL.Func([IDL.Text], [], []),
    'setLetter' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setMemories' : IDL.Func([IDL.Vec(Memory)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };